language: php

php:
    - 5.4
    - 5.6
    - 7.0
    - hhvm

env:
    - SYMFONY_VERSION=2.8.*

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction --prefer-source --dev
    - composer require videlalvaro/php-amqplib:2.2.*
    - composer require react/event-loop:0.4.*
    - composer require zendframework/zend-json:2.0.*

script:
    - phpunit --coverage-text

matrix:
    include:
      - php: 5.4
        env: SYMFONY_VERSION=2.3.*
      - php: 7.0
        env: SYMFONY_VERSION=3.0.*@dev
    allow_failures:
      - env: SYMFONY_VERSION=3.0.*@dev

services:
    rabbitmq
